//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sp.Samples.LicenseManagement.Store.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;
    
    public partial class CatalogEntry
    {
		public int Id { get; set; }
		[Display( Name = "Product Name" )]
		public string ProductName { get; set; }
		[Display( Name = "Product Version" )]
		public string ProductVersion { get; set; }
		public string SkuId { get; set; }
		public string Blurb { get; set; }
		public Nullable<decimal> Price { get; set; }
    }
}
